### ISSUE TITLE
Demo Camera shears instead of rotating

### ISSUE THREAD

**Issue by Chownie** [KarlTheCool/Shader-Stacker#16]
![image](https://user-images.githubusercontent.com/550176/210190983-0897050b-7f33-46e0-8d96-e5a61559ef18.png)

Checked out the repo and I'm seeing a different result to the expected (Godot Beta 10). If I untick "ignore rotation" it now seems to render more correctly:

![image](https://user-images.githubusercontent.com/550176/210191019-4a6426f4-28a6-4a69-9752-a1befd64d02b.png)

Which is the intended default behaviour?

**Comment by CoolDotty** [comment]
2nd pic is intended. It seems like someone was changed in the latest beta. Looking into it

**Comment by CoolDotty** [comment]
You're right. [Camera2d.rotating was renamed and inverted to ignore_rotation](https://github.com/godotengine/godot/pull/64359). I've fixed this by making [StackCamera default to `ignore_rotation = false`](https://github.com/KarlTheCool/Shader-Stacker/pull/15/commits/ff4eed395405c9a0c73a584725e57ddf53c6cab8)
