### ISSUE TITLE
Stacks with same position but different Z-level can clip

### ISSUE THREAD

**Issue by Chownie** [KarlTheCool/Shader-Stacker#17]
![cap](https://user-images.githubusercontent.com/550176/210673744-603f9cb6-ceee-4a2c-997c-38ea43348b89.gif)

Scenario:

Two stacked sprites. A block with Z set to 0, a barrel at Z set to -16. For part of the rotation the stack underneath clips to show in front of the stack above.

I recall a similar issue in the older version and that was due to my poor usage, is this the same?

**Comment by Chownie** [comment]
Also I'm a huge fan of your work and have been using shader-stacker since I opened an issue back in 2021, just haven't had much to share back! Here's a little screen recording of an abandoned-ish multiplayer colony sim I was working on back in June 😄 (This is the 3d version semi-ported to godot 4)

https://user-images.githubusercontent.com/550176/210675460-e4ebfca5-b225-4f57-bfac-8b7a08119362.mp4

**Comment by CoolDotty** [comment]
Sorting at the moment doesn't consider SpriteStack Z values. You could make it happen by editing the [screen_top_down_sort function in StackCamera](https://github.com/KarlTheCool/Shader-Stacker/blob/master/addons/ShaderStacker/StackCamera/StackCamera.gd).

Maybe split them up based on Z, sort those with the existing code, and merge them back together?

**Comment by CoolDotty** [comment]
> Also I'm a huge fan of your work and have been using shader-stacker since I opened an issue back in 2021, just haven't had much to share back! Here's a little screen recording of an abandoned-ish multiplayer colony sim I was working on back in June 😄 (This is the 3d version semi-ported to godot 4)
> 2022-11-01_02-58-55.mp4

So cool !!!! Thanks for sharing!

**Comment by Chownie** [comment]
> Sorting at the moment doesn't consider SpriteStack Z values. You could make it happen by editing the [screen_top_down_sort function in StackCamera](https://github.com/KarlTheCool/Shader-Stacker/blob/master/addons/ShaderStacker/StackCamera/StackCamera.gd).
> 
> Maybe split them up based on Z, sort those with the existing code, and merge them back together?

I'll look into that, thanks for pointing it out! I'm a little more familiar with the 3D version so I wasn't sure where the sorting was happening. I'll chime back in with a PR when I have something 👍
